---
title: "counting_genes.all.data"
author: "Diana.kisakye"
date: "`r Sys.Date()`"
output:
  html_notebook:
    toc: yes
    toc_depth: 3
    toc_float: yes
    highlight: tango
    number_sections: no
    fig_caption: yes
    theme: sandstone
    code_folding: hide
---

## Load packages  
```{r}
rm(list = ls(all = TRUE))
library(magrittr)
library(dplyr)
library(ggplot2)
library(rstudioapi)
```

```{r setup_script, eval=TRUE, results='hide'}
# GET CURRENT SCRIPT NAME
(this.script <- rstudioapi::getActiveDocumentContext() %>% .$path %>% basename)
getwd()
list.files()
stopifnot(this.script != "")
```

## Data files  
### Upregulated genes  
```{r}

data.files.up <- list.files(path="data.out", pattern="genes\\.up\\.uniq.*", full.names = TRUE)
# cat(data.files.up, sep="\n")
# data_out/genes.up.uniq.bcg.discovery.txt
# data_out/genes.up.uniq.bcg.validation.txt
# data_out/genes.up.uniq.GSE103092.txt
# data_out/genes.up.uniq.GSE29731.txt
# data_out/genes.up.uniq.GSE34151.txt
# data_out/genes.up.uniq.mtb.discovery.txt
# data_out/genes.up.uniq.mtb.validation.txt
# data_out/genes.up.uniq.Taileux.dendritic.txt
# data_out/genes.up.uniq.Taileux.macrophages.txt
data.files.up
#basename(data.files.up)
```

### Downregulated genes  
```{r}
data.files.down <- list.files(path="data_out", pattern="genes\\.down\\.uniq.*", full.names = T)
basename(data.files.down)
```

### Load data: upregulated genes    
```{r}
genes.up <- lapply(data.files.up, function(f) {
  scan(file = f, what = "character")
}) %>% 
  magrittr::set_names(basename(data.files.up))
```

```{r}
# class(genes.up) # "list"
# length(genes.up) # 9
# sapply(genes.up, class)
# sapply(genes.up, length)
```


```{r}
data.frame(File=names(genes.up),
            Gene.count=sapply(genes.up, length)) %>% 
  knitr::kable(., row.names = F)
```

### Load data: downregulated genes    
```{r}
genes.down <- lapply(data.files.down, function(f) {
  scan(file = f, what = "character")
}) %>% 
  magrittr::set_names(basename(data.files.down))
```

```{r}
data.frame(File=names(genes.down),
            Gene.count=sapply(genes.down, length)) %>% 
  knitr::kable(., row.names = F)
```

## Number of regulated genes:
### Number of upregulated genes  
```{r}
up.all <- unlist(genes.up) %>% toupper
# class(up.all) # "character"
length(up.all) # 2883
```

```{r}
table.up   <- table(up.all) %>% as.data.frame(., stringsAsFactors = FALSE) %>%
  set_colnames(c("Gene", "Count")) %>%
  arrange(desc(Count))
# dim(table.up) # 1855    2
DT::datatable(table.up)
```

### Number of downregulated genes  
```{r}
down.all <- unlist(genes.down) %>% toupper
length(down.all) # 2998
```

```{r}
table.down <- table(down.all) %>% as.data.frame(.,stringsAsFactors = FALSE) %>%
  set_colnames(c("Gene", "Count")) %>%
  arrange(desc(Count))
DT::datatable(table.down)
```

```{r}
length(unique(table.up$Gene)) # 1855
```

```{r}
length(unique(table.down$Gene)) # 2064
```


```{r}
t.up.count <- table(table.up$Count) %>%
 as.data.frame(stringsAsFactors  = FALSE) %>%
  set_colnames(c("Count", "Freq")) 
knitr::kable(t.up.count)
# insert this as a table with all counts for both up and down regulated genes.
# extract gene symbols in 3 or more datasets and perform gene set enrichment analysis; enrichr
```

```{r}
t.down.count <- table(table.down$Count) %>%
 as.data.frame(stringsAsFactors  = FALSE) %>%
  set_colnames(c("Count", "Freq")) 
knitr::kable(t.down.count)
```

### Creating list of up-regulated genes with a count >= 3
```{r}
genes.up.min.3 <- table.up %>%
  filter(Count >= 3) %>%
  magrittr::use_series("Gene") %>% 
  unique %>% 
  sort
# genes.up.min.3
# length(genes.up.min.3) # 231
head(genes.up.min.3)
```

### Creating list of down-regulated genes with a count >= 3
```{r}
genes.down.min.3 <- table.down %>%
  filter(Count >=3) %>%
  # .$Gene %>% 
  magrittr::use_series("Gene") %>% 
  unique %>% 
  sort 
# head(genes.down) # "ACSL5"   "ADCY7"   "ADORA2A" "AIF1"    "AK4"     "ALDH3A2"
length(genes.down.min.3) # 213
```


## Save results  
```{r}
out.file.up <- paste0("data_out/", this.script, ".up_min3.txt")
cat(genes.up.min.3, file = out.file.up, sep = "\n" )
cat("File saved:", out.file.up)
```

```{r}
out.file.down <- paste0("data_out/", this.script, ".down_min3.txt")
cat(genes.down.min.3, file = out.file.down, sep = "\n" )
cat("File saved:", out.file.down)
```

